### ISSUE TITLE
APKit

### ISSUE THREAD

**Issue by mrtnstolk** [collinhundley/Swift-AI#40]
I get an error saying:
Module file was created by an older version of the compiler; rebuild 'APKit' and try again

when I try to run the iOS example project.

**Comment by KacheFlowe** [comment]
Ok. Please don't take this the wrong way but... Did you try to do what the compiler told you?

**Comment by mrtnstolk** [comment]
How would I rebuild the framework? Do I not need the source in order to rebuild?

**Comment by KacheFlowe** [comment]
Poor question in my part. What version of Xcode are you running?

**Comment by collinhundley** [comment]
@mrtnstolk @KacheFlowe You won't be able to fix that error without the APKit source, my apologies. It happens occasionally with new releases of Xcode (has to do with a module map that's used), but I've recently re-written a large part of the framework to solve that issue and make huge improvements. I'm not at my computer right now, but I can make those fixes soon.

**Comment by balram3429** [comment]
@collinhundley :+1: 

I am also facing the same issue due to **APKit.framework**. The Xcode (7.3) results into error to rebuild it. 
**"Module file was created by an older version of the compiler; rebuild 'APKit' and try again: /APKit.framework/Modules/APKit.swiftmodule/arm64.swiftmodule"**

It was fine with prior version of Xcode (7.2) which was using the BaseSDK iOS 9.2. The problem seems to be due to the BaseSDK iOS 9.3 with the recent Xcode release. Definitely the issue can be fixed only by rebuilding the Source code of APKit framework. 

Awaiting updates from you. 
Thank you

**Comment by KacheFlowe** [comment]
Ditto.

**Comment by collinhundley** [comment]
@balram3429 @KacheFlowe  You're right guys, I apologize for the inconvenience.  I've built an entirely new version of APKit with major improvements (and it eliminates compatibility problems with new versions of Xcode).  I haven't had the time to update Swift AI with it yet, but I will as soon as I get the chance (probably tomorrow).  Until then, the the Swift AI iOS app will not build with Xcode 7.3 so I'd recommend you build from 7.2 if possible.

**Comment by KacheFlowe** [comment]
@collinhundley You're a student bud; totally get it

**Comment by balram3429** [comment]
@KacheFlowe :+1:  @collinhundley :+1: :+1: 

Yea, I am now downloading the prior version of simulator to get the 9.2 as BaseSDK. Will be waiting for your update.

**Comment by raul1338** [comment]
same problem
Module file was created by an older version of the compiler; rebuild 'APKit' and try again

xcode 7.3

**Comment by wojtekcz** [comment]
What APKit is? If this dependency is important, perhaps its sources can be uploaded to github as well?

**Comment by KacheFlowe** [comment]
APkit is a dependency thatvI believe was written by Colin. I like that
idea. What say you, Colin?

**Comment by collinhundley** [comment]
@KacheFlowe @wojtekcz Yes, APKit is a library that a colleague and I have written to assist with Auto Layout, animations, math, and a plethora of other functions.  The dependency breaks on Xcode 7.3, but we've completely rewritten the library anyway to provide a much cleaner syntax.  As we speak, I'm in the middle of migrating Swift AI to use this new version of APKit, and I will include the source files for it as well, rather than just the .framework.  This should fix all the issues that have been occurring, and prevent situations like this from arising in the future.

One note:  I don't have time at the moment to do a very thorough testing of Swift AI using the new constraint methods, so I'll be leaving the old code commented out beneath where I made any changes.  That way, if I mistyped something and created the wrong constraints, we should be able to catch it by comparing to the old code.

**Comment by KacheFlowe** [comment]
Woo hoo!

**Comment by collinhundley** [comment]
Annnnd... pushed to master.  Let me know if you guys have any problems.

**Comment by wojtekcz** [comment]
iOS project builds with Xcode 7.3 and runs on my iPhone 6 Plus. Thanks a lot.

**Comment by KacheFlowe** [comment]
Reporting same. Huzzah.
