### ISSUE TITLE
Remove unnecessary use of `self`

### ISSUE THREAD

**Issue by collinhundley** [collinhundley/Swift-AI#45]
Following the rejection of [this proposal](https://github.com/apple/swift-evolution/blob/master/proposals/0009-require-self-for-accessing-instance-members.md), and conforming to its corresponding [rationale](https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20160104/005478.html), we will be removing all usage of `self` within Swift AI.  The obvious exceptions are instances where the compiler requires it (such as inside blocks), and in places where using `self` provides clarity which cannot otherwise be determined by the context.  These situations, however, are rare, so the general rule of thumb will be "if the compiler can figure it out, so can you."

**Comment by KacheFlowe** [comment]
"if the compiler can figure it out, so can you" should be on a t-shirt

**Comment by va3093** [comment]
Hey everyone. I have just come across this project and am looking at contributing on some of your outstanding tasks. I came across this issue and thought I would drop in my 2-cents. I have been developing on Swift since the beginning and would highly recommend keeping the use of `self` wherever possible. Having tried both approaches I think using self makes code much more readable because it indicates the scope of a variable at a glance. Yes the compiler doesn't need self, but this is only because it goes through a lot of effort to determine the scope of a variable. We don't want to add any effort to the readers of our code and I think using `self` is step in that direction. There are also some name shadowing bugs that crop up from not using `self`. Just some thoughts.

**Comment by pjebs** [comment]
I watched a video on WWDC where the presenter said that Apple's style guide was to include self everywhere.
