### ISSUE TITLE
number 7

### ISSUE THREAD

**Issue by githubhero** [collinhundley/Swift-AI#46]
Hey, maybe I can't write, but number 7 very often is not recognized.

Anyway, very good work.

**Comment by collinhundley** [comment]
I've always noticed the same problem, and frankly I haven't got the
slightest clue why.  I have the most trouble with 7's, followed closely by
9's and 4's.  The other numbers seem to work great.  Even if I completely
re-train the neural network, those numbers always seem to have the most
trouble.  I'm inclined to think that it has to do with the way I'm
windowing the canvas and downsizing the image, because the network achieves
98% on the test data so there's no reason it should have so much trouble
with our own handwriting.  If anybody else has ideas, I'd love to hear it!
