### ISSUE TITLE
GPU/Multi-thread CPU acceleration?

### ISSUE THREAD

**Issue by dkliman** [collinhundley/Swift-AI#47]
I was unsure from the docs, but will you be supporting these on OS X?

**Comment by collinhundley** [comment]
@dkliman Currently the feed-forward neural network (`FFNN`) uses Apple's Accelerate library to perform vector calculations concurrently under the hood. Since performance is limited to your processor's ability to handle SIMD instructions, I've found no real benefit to adding further multi-threading support using something like GCD. However, this is largely dependent on the hardware you're using. It's possible that some machines could see performance gains from multi-threading if the processor includes multiple SIMD execution units, but to my knowledge this isn't the case for any Apple-made hardware.

GPU acceleration, on the other hand, could give us a real advantage.  I'd love to implement a neural network using Metal in the near future.
